include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = revealloaderprefs

revealloaderprefs_FILES = revealloaderRootListController.m
revealloaderprefs_PRIVATE_FRAMEWORKS = Preferences
revealloaderprefs_INSTALL_PATH = /Library/PreferenceBundles
revealloaderprefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
